Repository meongmory/meongmory_server, pull requests merged in 2023-08, with the labels that each got.

#17 [Feat] 공지사항 목록 조회 API
  build.gradle
  src/main/java/com/meongmory/meongmory/domain/cs/controller/CsController.java
  src/main/java/com/meongmory/meongmory/domain/cs/dto/assembler/CsAssembler.java
  src/main/java/com/meongmory/meongmory/domain/cs/dto/response/GetNoticesRes.java
  src/main/java/com/meongmory/meongmory/domain/cs/dto/response/NoticeRes.java
  src/main/java/com/meongmory/meongmory/domain/cs/entity/Inquiry.java
  src/main/java/com/meongmory/meongmory/domain/cs/entity/Notice.java
  src/main/java/com/meongmory/meongmory/domain/cs/repository/NoticeRepository.java
  src/main/java/com/meongmory/meongmory/domain/cs/service/CsService.java
Labels: 🦋 feature

#19 [Feat] 회원가입 API 기능
  build.gradle
  src/main/java/com/meongmory/meongmory/domain/user/UserService.java
  src/main/java/com/meongmory/meongmory/domain/user/controller/UserController.java
  src/main/java/com/meongmory/meongmory/domain/user/dto/request/SignUpUserReq.java
  src/main/java/com/meongmory/meongmory/domain/user/dto/request/UserAuthTokenReqest.java
  src/main/java/com/meongmory/meongmory/domain/user/dto/response/SignUpUserRes.java
  src/main/java/com/meongmory/meongmory/domain/user/entity/User.java
  src/main/java/com/meongmory/meongmory/domain/user/repository/UserRepository.java
  src/main/java/com/meongmory/meongmory/domain/user/service/UserService.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
  src/main/java/com/meongmory/meongmory/global/util/TokenUtil.java
Labels: 🐞 fix, 🦋 feature

#28 [Feat] 다이어리 상세조회 API
  src/main/java/com/meongmory/meongmory/domain/diary/controller/DiaryController.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/assembler/DiaryAssembler.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/CommentRes.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/DetailDiaryRes.java
  src/main/java/com/meongmory/meongmory/domain/diary/repository/DiaryCommentRepository.java
  src/main/java/com/meongmory/meongmory/domain/diary/repository/DiaryRepository.java
  src/main/java/com/meongmory/meongmory/domain/diary/service/DiaryServiceImpl.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
Labels: 🦋 feature

#20 [Feat] 다이어리 조회 (갤러리형식, 리스트형식) 기능개발
  src/main/java/com/meongmory/meongmory/MeongmoryApplication.java
  src/main/java/com/meongmory/meongmory/domain/diary/controller/DiaryController.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/assembler/DiaryAssembler.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/request/RecordDiaryReq.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/CommentRes.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/DetailDiaryRes.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/FileRes.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/GalleryTypeRes.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/GetDiariesRes.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/ListTypeRes.java
  src/main/java/com/meongmory/meongmory/domain/diary/entity/Diary.java
  src/main/java/com/meongmory/meongmory/domain/diary/entity/SortType.java
  src/main/java/com/meongmory/meongmory/domain/diary/repository/DiaryCommentRepository.java
  src/main/java/com/meongmory/meongmory/domain/diary/repository/DiaryRepository.java
  src/main/java/com/meongmory/meongmory/domain/diary/service/DiaryService.java
  src/main/java/com/meongmory/meongmory/domain/diary/service/DiaryServiceImpl.java
  src/main/java/com/meongmory/meongmory/domain/family/FamilyController.java
  src/main/java/com/meongmory/meongmory/domain/family/controller/FamilyController.java
  src/main/java/com/meongmory/meongmory/domain/family/entity/Family.java
  src/main/java/com/meongmory/meongmory/domain/family/entity/Pet.java
  src/main/java/com/meongmory/meongmory/domain/family/repository/FamilyMemberRepository.java
  src/main/java/com/meongmory/meongmory/domain/family/repository/FamilyRepository.java
  src/main/java/com/meongmory/meongmory/domain/family/repository/PetRepository.java
  src/main/java/com/meongmory/meongmory/domain/user/repository/UserRepository.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
Labels: 🦋 feature

#21 [Feat] 공지사항 상세 조회 API
  src/main/java/com/meongmory/meongmory/domain/cs/controller/CsController.java
  src/main/java/com/meongmory/meongmory/domain/cs/dto/assembler/CsAssembler.java
  src/main/java/com/meongmory/meongmory/domain/cs/dto/response/GetNoticeDetailRes.java
  src/main/java/com/meongmory/meongmory/domain/cs/repository/NoticeRepository.java
  src/main/java/com/meongmory/meongmory/domain/cs/service/CsService.java
  src/main/java/com/meongmory/meongmory/global/config/SwaggerConfig.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseRes.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
Labels: 🦋 feature

#23 [Feat] 문의하기 API
  build.gradle
  src/main/java/com/meongmory/meongmory/domain/cs/controller/CsController.java
  src/main/java/com/meongmory/meongmory/domain/cs/dto/assembler/CsAssembler.java
  src/main/java/com/meongmory/meongmory/domain/cs/dto/request/CreateInquiryReq.java
  src/main/java/com/meongmory/meongmory/domain/cs/repository/InquiryRepository.java
  src/main/java/com/meongmory/meongmory/domain/cs/service/CsService.java
  src/main/java/com/meongmory/meongmory/domain/user/repository/UserRepository.java
  src/main/java/com/meongmory/meongmory/global/config/SwaggerConfig.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
Labels: 🦋 feature

#25 [Feat] 알림 목록 조회 API
  src/main/java/com/meongmory/meongmory/domain/notification/controller/NotificationController.java
  src/main/java/com/meongmory/meongmory/domain/notification/dto/assembler/NotificationAssembler.java
  src/main/java/com/meongmory/meongmory/domain/notification/dto/response/GetNotificationsRes.java
  src/main/java/com/meongmory/meongmory/domain/notification/dto/response/NotificationDetail.java
  src/main/java/com/meongmory/meongmory/domain/notification/entity/Notification.java
  src/main/java/com/meongmory/meongmory/domain/notification/entity/NotificationType.java
  src/main/java/com/meongmory/meongmory/domain/notification/repository/NotificationRepository.java
  src/main/java/com/meongmory/meongmory/domain/notification/service/NotificationService.java
  src/main/java/com/meongmory/meongmory/domain/user/repository/UserRepository.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
Labels: 🦋 feature

#30 [Feat] Fcm 설정 추가
  .gitignore
  src/main/java/com/meongmory/meongmory/domain/notification/dto/FcmMessage.java
  src/main/java/com/meongmory/meongmory/domain/notification/dto/Message.java
  src/main/java/com/meongmory/meongmory/domain/notification/dto/Notification.java
  src/main/java/com/meongmory/meongmory/domain/notification/service/FcmService.java
  src/main/java/com/meongmory/meongmory/domain/user/entity/User.java
Labels: 🦋 feature

#32 [Refactor] response 변경 및 충돌 해결
  src/main/java/com/meongmory/meongmory/domain/cs/controller/CsController.java
  src/main/java/com/meongmory/meongmory/domain/cs/dto/assembler/CsAssembler.java
  src/main/java/com/meongmory/meongmory/domain/cs/service/CsService.java
  src/main/java/com/meongmory/meongmory/domain/notification/service/NotificationService.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseException.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseRes.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
  src/main/java/com/meongmory/meongmory/global/exception/ExceptionHandlerAdvice.java
Labels: 🐹 refactor

#34 [Setting] Swagger 토큰등록, QueryDsl Setting
  src/main/java/com/meongmory/meongmory/global/config/QueryDslConfig.java
  src/main/java/com/meongmory/meongmory/global/config/SwaggerConfig.java
Labels: 🐸 setting

#37 [Refactor] validation BaseResponseCode 적용 방법 구상
  src/main/java/com/meongmory/meongmory/domain/cs/dto/request/CreateInquiryReq.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
  src/main/java/com/meongmory/meongmory/global/exception/ExceptionHandlerAdvice.java
Labels: 🐹 refactor, ❓ question

#38 [Setting] 레디스 임시 설정
  build.gradle
  src/main/java/com/meongmory/meongmory/domain/user/service/UserService.java
  src/main/java/com/meongmory/meongmory/global/config/RedisConfig.java
  src/main/java/com/meongmory/meongmory/global/util/redis/RedisServiceMock.java
  src/main/java/com/meongmory/meongmory/global/util/redis/RedisTemplateService.java
  src/main/java/com/meongmory/meongmory/global/util/redis/RedisUtils.java
  src/main/java/com/meongmory/meongmory/global/util/token/TokenUtil.java
Labels: 🐸 setting

#42 [Refactor] Response 통일
  src/main/java/com/meongmory/meongmory/domain/cs/controller/CsController.java
  src/main/java/com/meongmory/meongmory/domain/user/controller/UserController.java
  src/main/java/com/meongmory/meongmory/global/config/SwaggerConfig.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseRes.java
  src/main/java/com/meongmory/meongmory/global/exception/ExceptionHandlerAdvice.java
  src/main/java/com/meongmory/meongmory/global/response/ResponseCustom.java
Labels: 🐹 refactor

#44 [FEAT] 펫 다이어리(가족) 생성 API
  build.gradle
  src/main/java/com/meongmory/meongmory/domain/family/controller/FamilyController.java
  src/main/java/com/meongmory/meongmory/domain/family/dto/request/CreateFamilyReq.java
  src/main/java/com/meongmory/meongmory/domain/family/entity/Family.java
  src/main/java/com/meongmory/meongmory/domain/family/entity/FamilyMember.java
  src/main/java/com/meongmory/meongmory/domain/family/repository/FamilyMemberRepository.java
  src/main/java/com/meongmory/meongmory/domain/family/service/FamilyService.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
  src/main/java/com/meongmory/meongmory/global/util/Constant.java
Labels: 🦋 feature

#46 [Fix] 연관관계 재설정 오류 해결
  src/main/java/com/meongmory/meongmory/domain/diary/controller/DiaryController.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/request/RecordDiaryFileKeyReq.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/request/RecordDiaryPetReq.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/request/RecordDiaryReq.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/ListTypeRes.java
  src/main/java/com/meongmory/meongmory/domain/diary/entity/Diary.java
  src/main/java/com/meongmory/meongmory/domain/diary/entity/DiaryFile.java
  src/main/java/com/meongmory/meongmory/domain/diary/entity/DiaryPet.java
  src/main/java/com/meongmory/meongmory/domain/diary/entity/FileType.java
  src/main/java/com/meongmory/meongmory/domain/diary/entity/Scope.java
  src/main/java/com/meongmory/meongmory/domain/diary/repository/DiaryFileRepository.java
  src/main/java/com/meongmory/meongmory/domain/diary/repository/DiaryPetRepository.java
  src/main/java/com/meongmory/meongmory/domain/diary/repository/DiaryRepository.java
  src/main/java/com/meongmory/meongmory/domain/diary/service/DiaryService.java
  src/main/java/com/meongmory/meongmory/domain/diary/service/DiaryServiceImpl.java
  src/main/java/com/meongmory/meongmory/domain/family/entity/Family.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
  src/main/java/com/meongmory/meongmory/global/util/AwsS3ImageUrlUtil.java
Labels: 🦑 hotfix

#47 [Feat] SMS 문자인증 API
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
  src/main/java/com/meongmory/meongmory/global/util/redis/RedisServiceMock.java
  src/main/java/com/meongmory/meongmory/global/util/redis/RedisTemplateService.java
  src/main/java/com/meongmory/meongmory/global/util/redis/RedisTemplateServiceImpl.java
  src/main/java/com/meongmory/meongmory/global/util/sms/controller/SmsController.java
  src/main/java/com/meongmory/meongmory/global/util/sms/dto/MessageDto.java
  src/main/java/com/meongmory/meongmory/global/util/sms/dto/SmsNaverReq.java
  src/main/java/com/meongmory/meongmory/global/util/sms/dto/SmsSendReq.java
  src/main/java/com/meongmory/meongmory/global/util/sms/dto/SmsSendRes.java
  src/main/java/com/meongmory/meongmory/global/util/sms/dto/SmsValidationReq.java
  src/main/java/com/meongmory/meongmory/global/util/sms/service/SmsService.java
Labels: 🐞 fix, 🦋 feature

#49 [Feat] 다이어리 등록 API
  src/main/java/com/meongmory/meongmory/domain/diary/controller/DiaryController.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/request/RecordDiaryPetReq.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/request/RecordDiaryReq.java
  src/main/java/com/meongmory/meongmory/domain/diary/entity/Scope.java
  src/main/java/com/meongmory/meongmory/domain/diary/service/DiaryServiceImpl.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
Labels: 🦋 feature, 🐹 refactor

#51 [Refactor] 다이어리 조회, 다이어리 상세조회 수정
  src/main/java/com/meongmory/meongmory/domain/diary/controller/DiaryController.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/DetailDiaryRes.java
  src/main/java/com/meongmory/meongmory/domain/diary/entity/DiaryFile.java
  src/main/java/com/meongmory/meongmory/domain/diary/repository/DiaryPetRepository.java
  src/main/java/com/meongmory/meongmory/domain/diary/service/DiaryServiceImpl.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
Labels: 🦋 feature, 🐹 refactor

#56 [Feat] 다이어리 댓글 등록 API
  src/main/java/com/meongmory/meongmory/domain/diary/controller/DiaryController.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/RecordCommentReq.java
  src/main/java/com/meongmory/meongmory/domain/diary/entity/DiaryComment.java
  src/main/java/com/meongmory/meongmory/domain/diary/service/DiaryService.java
  src/main/java/com/meongmory/meongmory/domain/diary/service/DiaryServiceImpl.java
Labels: 🦋 feature

#61 [Refactor] CS 관련 스웨거, 어셈블러 수정
  src/main/java/com/meongmory/meongmory/domain/cs/controller/CsController.java
  src/main/java/com/meongmory/meongmory/domain/cs/dto/assembler/CsAssembler.java
  src/main/java/com/meongmory/meongmory/domain/cs/dto/request/CreateInquiryReq.java
  src/main/java/com/meongmory/meongmory/domain/cs/dto/response/GetNoticeDetailRes.java
  src/main/java/com/meongmory/meongmory/domain/cs/dto/response/GetNoticesRes.java
  src/main/java/com/meongmory/meongmory/domain/cs/dto/response/NoticeRes.java
  src/main/java/com/meongmory/meongmory/domain/cs/entity/Inquiry.java
  src/main/java/com/meongmory/meongmory/domain/cs/service/CsService.java
Labels: 🐹 refactor

#62 [Feat] 반려동물 API
  src/main/java/com/meongmory/meongmory/domain/family/controller/FamilyController.java
  src/main/java/com/meongmory/meongmory/domain/family/dto/request/CreateFamilyPetReq.java
  src/main/java/com/meongmory/meongmory/domain/family/entity/Gender.java
  src/main/java/com/meongmory/meongmory/domain/family/entity/Pet.java
  src/main/java/com/meongmory/meongmory/domain/family/repository/AnimalRepository.java
  src/main/java/com/meongmory/meongmory/domain/family/service/FamilyService.java
  src/main/java/com/meongmory/meongmory/global/entity/AnimalType.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
Labels: 🦋 feature

#64 [Refactor] diary controller authentication 적용
  build.gradle
  src/main/java/com/meongmory/meongmory/domain/diary/controller/DiaryController.java
Labels: 🐹 refactor

#65 [Feat] 로그인 기능 API
  src/main/java/com/meongmory/meongmory/global/config/WebConfig.java
Labels: 🦋 feature

#74 [Fix] CS & 알림 Authentication 설정 및 알림 스웨거 적용
  src/main/java/com/meongmory/meongmory/domain/cs/controller/CsController.java
  src/main/java/com/meongmory/meongmory/domain/notification/controller/NotificationController.java
  src/main/java/com/meongmory/meongmory/domain/notification/dto/response/NotificationDetail.java
Labels: 🐞 fix, 🐹 refactor

#75 [Feat] accessToken 재발급 API
  src/main/java/com/meongmory/meongmory/domain/user/controller/UserAuthController.java
  src/main/java/com/meongmory/meongmory/domain/user/dto/request/UserAuthTokenReqest.java
  src/main/java/com/meongmory/meongmory/domain/user/dto/request/UserAuthTokenRequest.java
  src/main/java/com/meongmory/meongmory/domain/user/entity/User.java
  src/main/java/com/meongmory/meongmory/domain/user/service/UserService.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
  src/main/java/com/meongmory/meongmory/global/util/token/TokenUtil.java
Labels: 🦋 feature

#82 [Feature] 다이어리 조회, 상세조회 API
  src/main/java/com/meongmory/meongmory/domain/diary/controller/DiaryController.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/assembler/DiaryAssembler.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/FileRes.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/GalleryTypeRes.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/GetDiariesRes.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/ListTypeRes.java
  src/main/java/com/meongmory/meongmory/domain/diary/dto/response/PetNameRes.java
  src/main/java/com/meongmory/meongmory/domain/diary/entity/Diary.java
  src/main/java/com/meongmory/meongmory/domain/diary/entity/DiaryFile.java
  src/main/java/com/meongmory/meongmory/domain/diary/entity/DiaryPet.java
  src/main/java/com/meongmory/meongmory/domain/diary/service/DiaryService.java
  src/main/java/com/meongmory/meongmory/domain/diary/service/DiaryServiceImpl.java
Labels: 🦋 feature, 🐹 refactor, ❓ question

#86 [Feat] 펫 다이어리 가족, 친구 삭제 API
  src/main/java/com/meongmory/meongmory/domain/family/controller/FamilyController.java
  src/main/java/com/meongmory/meongmory/domain/family/service/FamilyService.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
Labels: 🦋 feature

#88 [Refactor] 유저 도메인 리팩토링
  src/main/java/com/meongmory/meongmory/domain/user/controller/UserAuthController.java
  src/main/java/com/meongmory/meongmory/domain/user/controller/UserController.java
  src/main/java/com/meongmory/meongmory/domain/user/dto/request/UserAuthTokenRequest.java
  src/main/java/com/meongmory/meongmory/domain/user/entity/User.java
  src/main/java/com/meongmory/meongmory/domain/user/service/UserService.java
  src/main/java/com/meongmory/meongmory/global/util/token/TokenUtil.java
Labels: 🐹 refactor

#89 [Feat] 펫 다이어리 가족, 친구 초대 API
  src/main/java/com/meongmory/meongmory/domain/family/controller/FamilyController.java
  src/main/java/com/meongmory/meongmory/domain/family/dto/request/InviteFamilyMemberReq.java
  src/main/java/com/meongmory/meongmory/domain/family/repository/FamilyMemberRepository.java
  src/main/java/com/meongmory/meongmory/domain/family/repository/FamilyRepository.java
  src/main/java/com/meongmory/meongmory/domain/family/service/FamilyService.java
  src/main/java/com/meongmory/meongmory/global/exception/BaseResponseCode.java
Labels: 🦋 feature

#90 [Feat] familyController Token 적용
  src/main/java/com/meongmory/meongmory/domain/family/controller/FamilyController.java
Labels: 🦋 feature
